/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swamisamarth.main;

import com.swamisamarth.utils.CommonUtil;
import com.swamisamarth.utils.LoadFont;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author SUPRIYA
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        try {
            CommonUtil.setLanguage("Marathi");
            initComponents();
            setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
            setFont("Marathi");
//            JLabel background = new JLabel(new ImageIcon("images\\loginBack.jpg"));
//            add(background);
//            background.setLayout(new FlowLayout());
            Font f = LoadFont.getFont().deriveFont(Font.BOLD, 18);
            lblMarathi.setFont(f);
            lblMarathi.setText("marazI");

            Font f1 = new Font("Courier", Font.BOLD, 14);
            lblEnglish.setFont(f1);

            ImageIcon img = new ImageIcon("Images/samarth01.jpg");
            setTitle("Swami Samrth Mandal");
            setIconImage(img.getImage());

            txtUserName.setBorder(BorderFactory.createCompoundBorder(txtUserName.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));
            jPasswordField1.setBorder(BorderFactory.createCompoundBorder(jPasswordField1.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));
            jPanel4.setOpaque(false);

        } catch (Exception ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setFont(String lang) {

        if (lang.equalsIgnoreCase("english")) {
            Font f1 = new Font("Courier", Font.BOLD, 14);
            lblUserName.setFont(f1);
            lblPassword.setFont(f1);
            txtUserName.setFont(f1);
        } else {
            Font f = LoadFont.getFont().deriveFont(Font.BOLD, 18);
            lblUserName.setFont(f);
            lblPassword.setFont(f);
            txtUserName.setFont(f);

        }
        lblUserName.setText(CommonUtil.getResourceProperty("loginUsername"));
        lblPassword.setText(CommonUtil.getResourceProperty("loginPassword"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMarathi = new javax.swing.JLabel();
        lblEnglish = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel(){
            protected int strokeSize = 1;
            /** Color of shadow */
            protected Color shadowColor = new Color(153,195,47);
            /** Sets if it drops shadow */
            protected boolean shady = true;
            /** Sets if it has an High Quality view */
            protected boolean highQuality = true;
            /** Double values for Horizontal and Vertical radius of corner arcs */
            protected Dimension arcs = new Dimension(20, 20);
            /** Distance between shadow border and opaque panel border */
            protected int shadowGap = 7;
            /** The offset of shadow.  */
            protected int shadowOffset = 4;
            /** The transparency value of shadow. ( 0 - 255) */
            protected int shadowAlpha = 150;

            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                int width = getWidth();
                int height = getHeight();
                int shadowGap = this.shadowGap;
                Color shadowColorA = new Color(shadowColor.getRed(),
                    shadowColor.getGreen(), shadowColor.getBlue(), shadowAlpha);
                Graphics2D graphics = (Graphics2D) g;

                //Sets antialiasing if HQ.
                if (highQuality) {
                    graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                        RenderingHints.VALUE_ANTIALIAS_ON);
                }

                //Draws shadow borders if any.
                if (shady) {
                    graphics.setColor(shadowColorA);
                    graphics.fillRoundRect(
                        shadowOffset,// X position
                        shadowOffset,// Y position
                        width - strokeSize - shadowOffset, // width
                        height - strokeSize - shadowOffset, // height
                        arcs.width, arcs.height);// arc Dimension
                } else {
                    shadowGap = 1;
                }

                //Draws the rounded opaque panel with borders.
                graphics.setColor(getBackground());
                graphics.fillRoundRect(0, 0, width - shadowGap,
                    height - shadowGap, arcs.width, arcs.height);
                graphics.setColor(getForeground());
                graphics.setStroke(new BasicStroke(strokeSize));
                graphics.drawRoundRect(0, 0, width - shadowGap,
                    height - shadowGap, arcs.width, arcs.height);

                //Sets strokes to default, is better.
                graphics.setStroke(new BasicStroke());
            }
        };
        txtUserName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        butLogin = new javax.swing.JButton();
        lblForgotPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 195, 47));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblMarathi.setForeground(new java.awt.Color(255, 255, 255));
        lblMarathi.setText("Marathi");
        lblMarathi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMarathiMouseClicked(evt);
            }
        });

        lblEnglish.setForeground(new java.awt.Color(255, 255, 255));
        lblEnglish.setText("English");
        lblEnglish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnglishMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(750, Short.MAX_VALUE)
                .addComponent(lblMarathi)
                .addGap(18, 18, 18)
                .addComponent(lblEnglish)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblMarathi, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(lblEnglish))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        txtUserName.setBorder(null);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("jLabel1");

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("jLabel2");

        butLogin.setBackground(new java.awt.Color(153, 195, 47));
        butLogin.setForeground(new java.awt.Color(255, 255, 255));
        butLogin.setText("SIGN IN");
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });

        lblForgotPassword.setText("jLabel1");

        jPasswordField1.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 195, 47));
        jLabel2.setText("LOGIN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                        .addComponent(butLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                        .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUserName)
                        .addComponent(lblForgotPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(butLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblForgotPassword)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\MySociety\\MySociety\\SwamiSamarth\\images\\swami.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void lblMarathiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarathiMouseClicked
        // TODO add your handling code here:
        lblMarathi.setBackground(Color.red);
        CommonUtil.setLanguage("Marathi");
        setFont("Marathi");
        this.invalidate();
        this.validate();
    }//GEN-LAST:event_lblMarathiMouseClicked

    private void lblEnglishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnglishMouseClicked
        // TODO add your handling code here:
        CommonUtil.setLanguage("English");

        setFont("English");
        this.invalidate();
        this.validate();

    }//GEN-LAST:event_lblEnglishMouseClicked

    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        this.setVisible(false);
        new FrmDashboard().setVisible(true);
    }//GEN-LAST:event_butLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblEnglish;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblMarathi;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
